#!/usr/bin/env python3
"""Generates standalone/<name>.sh: a single, SELF-CONTAINED bash script, meant
to be pasted whole into a terminal session on the Local cloud domain jumphost
(where transferring files is hard, but pasting a block of text is easy).

The generated script:
  1. Writes run_probe.py into a LOCAL temp directory on the jumphost/VM
     (no scp/external transfer needed: the content travels embedded).
  2. Writes the spec subset (automatable tests whose source.type
     matches --source-type, VM by default) as spec.json, also local.
  3. Runs the tests with `docker run --network host nicolaka/netshoot:v0.15`.
  4. Dumps the resulting log and its structured JSON companion to stdout
     (`cat`) so the operator can copy both outputs and save them in
     outputs/ on the lab PC (same basename, `.log` and `.json`).
  5. Drops the operator into an interactive `docker run -it` shell with
     run_probe.py + spec.json still present at /data, to run ad hoc
     `list`/`tcp`/`udp` subcommands (see README.md section 4.2) before the
     temp directory is cleaned up on exit.

Runs on the dev PC with `uv run src/generate_standalone_script.py`.
Only uses the standard library.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from suite_common import ROOT, check_suite_exists, resolve_config_path, resolve_suite

DEFAULT_PROBE = ROOT / "src" / "run_probe.py"


SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
# SELF-CONTAINED script for Local cloud domain (VM) -> Remote cloud domain connectivity tests.
# Generated by src/generate_standalone_script.py -- do not edit by hand.
#
# Usage: paste this whole file into the jumphost/VM terminal session
# (or run it if it was somehow copied over), and at the end copy the log
# and the structured JSON results block printed to screen into two files
# inside {outputs_dir_display}/ on the lab PC, with the SAME basename, e.g.:
#   {outputs_dir_display}/local-cloud-domain-to-remote-cloud-domain-vm-tests-$(date +%Y%m%dT%H%M%S).log
#   {outputs_dir_display}/local-cloud-domain-to-remote-cloud-domain-vm-tests-$(date +%Y%m%dT%H%M%S).json
# (the matching basename lets `uv run src/generate_report.py --suite <suite>`
# find both later)
# After the log is printed, you land inside an interactive shell with
# run_probe.py + spec.json still available, for ad hoc single-case tests
# (see README.md section 4.2). Type 'exit' to leave and clean up.
#
# Requires: docker installed with network egress to Remote cloud domain (same
# egress IP as the VM, thanks to --network host).
set -euo pipefail

WORKDIR="$(mktemp -d /tmp/conntest.XXXXXX)"
trap 'rm -rf "$WORKDIR"' EXIT

cat > "$WORKDIR/run_probe.py" <<'PROBE_PY_EOF'
{probe_source}
PROBE_PY_EOF

cat > "$WORKDIR/spec.json" <<'SPEC_JSON_EOF'
{spec_json}
SPEC_JSON_EOF

cat > "$WORKDIR/connectivity-tests.toml" <<'PROBE_TOML_EOF'
{probe_config}
PROBE_TOML_EOF

echo "Running {n_tests} connectivity tests (source.type={source_type}) via docker/netshoot..." >&2

docker run --rm --network host -v "$WORKDIR:/data" nicolaka/netshoot:v0.15 \\
  python3 /data/run_probe.py batch --spec /data/spec.json --config /data/connectivity-tests.toml --out /data/result.log

echo "" >&2
echo "===== LOG START (copy from here to the END marker into outputs/ on the lab PC) =====" >&2
cat "$WORKDIR/result.log"
echo "===== LOG END =====" >&2

echo "" >&2
echo "===== RESULTS_JSON START (save as the matching outputs/<suite>/logs/<same-basename>.json) =====" >&2
cat "$WORKDIR/result.json"
echo "===== RESULTS_JSON END =====" >&2

echo "" >&2
echo "Entering an interactive shell with run_probe.py + spec.json for ad hoc tests." >&2
echo "Examples: python3 /data/run_probe.py list --spec /data/spec.json" >&2
echo "          python3 /data/run_probe.py tcp <ip> <port>" >&2
echo "          python3 /data/run_probe.py udp <ip> <port> --config /data/connectivity-tests.toml" >&2
echo "Type 'exit' to leave and clean up temp files." >&2
docker run --rm -it --network host -v "$WORKDIR:/data" nicolaka/netshoot:v0.15 bash
"""


def build_filtered_spec(spec_path: Path, source_type: str, suite: str) -> dict:
    if not spec_path.exists():
        raise SystemExit(
            f"❌ Spec not found: {spec_path}\n"
            "   Generate it first with: uv run src/generate_test_spec.py "
            f"--suite {suite}"
        )
    with spec_path.open(encoding="utf-8") as f:
        spec = json.load(f)
    tests = [
        t
        for t in spec.get("tests", [])
        if t.get("automatable") and t["source"].get("type") == source_type
    ]
    return {
        "metadata": {**spec.get("metadata", {}), "filtered_for_source_type": source_type},
        "tests": tests,
        "unresolved": [],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--suite",
        default=None,
        help="Suite name (subfolder under inputs//outputs/; config is read from "
        "inputs/<suite>/connectivity-tests.toml if present). Falls back to the "
        "TEST_SUITE environment variable, and finally to the 'default' suite, if omitted.",
    )
    parser.add_argument("--spec", type=Path, default=None)
    parser.add_argument("--probe", type=Path, default=DEFAULT_PROBE)
    parser.add_argument("--probe-config", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--source-type", default="VM", help="source.type to include (default: VM)")
    args = parser.parse_args()

    suite = resolve_suite(args.suite)
    if args.spec is None:
        check_suite_exists(suite)
    spec = args.spec or ROOT / "inputs" / suite / "connectivity-test-spec.json"
    probe_config_path = resolve_config_path(args.probe_config, suite)
    out = args.out or ROOT / "outputs" / suite / "standalone" / "local-cloud-domain-to-remote-cloud-domain-vm-tests.sh"
    outputs_dir_display = f"outputs/{suite}/logs"

    probe_source = args.probe.read_text(encoding="utf-8")
    probe_config = probe_config_path.read_text(encoding="utf-8") if probe_config_path.exists() else ""
    filtered = build_filtered_spec(spec, args.source_type, suite)
    spec_json = json.dumps(filtered, indent=2, ensure_ascii=False)

    delimiters = {
        "PROBE_PY_EOF": probe_source,
        "SPEC_JSON_EOF": spec_json,
        "PROBE_TOML_EOF": probe_config,
    }
    for delimiter, content in delimiters.items():
        if delimiter in content:
            raise SystemExit(
                f"Heredoc delimiter collision: embedded content contains '{delimiter}'. "
                "Rename the delimiters in the template."
            )

    script = SCRIPT_TEMPLATE.format(
        probe_source=probe_source,
        spec_json=spec_json,
        probe_config=probe_config,
        n_tests=len(filtered["tests"]),
        source_type=args.source_type,
        outputs_dir_display=outputs_dir_display,
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(script, encoding="utf-8")
    out.chmod(0o755)
    print(f"✅ Generated {out} ({len(filtered['tests'])} tests, source.type={args.source_type})")


if __name__ == "__main__":
    sys.exit(main())
