#!/usr/bin/env python3
"""Generates standalone/<name>.sh: a single, SELF-CONTAINED bash script, meant
to be pasted whole into a terminal session on the Local cloud domain jumphost
(where transferring files is hard, but pasting a block of text is easy).

The generated script:
  1. Writes run_probe.py into a LOCAL temp directory on the jumphost/VM
     (no scp/external transfer needed: the content travels embedded).
  2. Writes the spec subset (automatable tests whose source.type
     matches --source-type, VM by default) as spec.json, also local.
  3. Runs the tests with `docker run --network host nicolaka/netshoot:v0.15`.
  4. Dumps the resulting log to stdout (`cat`) so the operator can copy the
     output and save it in outputs/ on the lab PC.

Runs on the dev PC with `uv run src/generate_standalone_script.py`.
Only uses the standard library.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SPEC = ROOT / "inputs" / "connectivity-test-spec.json"
DEFAULT_PROBE = ROOT / "src" / "run_probe.py"
DEFAULT_PROBE_CONFIG = ROOT / "connectivity-tests.toml"
DEFAULT_OUT = ROOT / "standalone" / "local-cloud-domain-to-remote-cloud-domain-vm-tests.sh"

SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
# SELF-CONTAINED script for Local cloud domain (VM) -> Remote cloud domain connectivity tests.
# Generated by src/generate_standalone_script.py -- do not edit by hand.
#
# Usage: paste this whole file into the jumphost/VM terminal session
# (or run it if it was somehow copied over), and at the end copy the log
# printed to screen into a file inside outputs/ on the lab
# PC, e.g.:
#   outputs/local-cloud-domain-to-remote-cloud-domain-vm-tests-$(date +%Y%m%dT%H%M%S).log
#
# Requires: docker installed with network egress to Remote cloud domain (same
# egress IP as the VM, thanks to --network host).
set -euo pipefail

WORKDIR="$(mktemp -d /tmp/conntest.XXXXXX)"
trap 'rm -rf "$WORKDIR"' EXIT

cat > "$WORKDIR/run_probe.py" <<'PROBE_PY_EOF'
{probe_source}
PROBE_PY_EOF

cat > "$WORKDIR/spec.json" <<'SPEC_JSON_EOF'
{spec_json}
SPEC_JSON_EOF

cat > "$WORKDIR/connectivity-tests.toml" <<'PROBE_TOML_EOF'
{probe_config}
PROBE_TOML_EOF

echo "Running {n_tests} connectivity tests (source.type={source_type}) via docker/netshoot..." >&2

docker run --rm --network host -v "$WORKDIR:/data" nicolaka/netshoot:v0.15 \\
  python3 /data/run_probe.py --spec /data/spec.json --config /data/connectivity-tests.toml --out /data/result.log

echo "" >&2
echo "===== LOG START (copy from here to the END marker into outputs/ on the lab PC) =====" >&2
cat "$WORKDIR/result.log"
echo "===== LOG END =====" >&2
"""


def build_filtered_spec(spec_path: Path, source_type: str) -> dict:
    with spec_path.open(encoding="utf-8") as f:
        spec = json.load(f)
    tests = [
        t
        for t in spec.get("tests", [])
        if t.get("automatable") and t["source"].get("type") == source_type
    ]
    return {
        "metadata": {**spec.get("metadata", {}), "filtered_for_source_type": source_type},
        "tests": tests,
        "unresolved": [],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    parser.add_argument("--probe", type=Path, default=DEFAULT_PROBE)
    parser.add_argument("--probe-config", type=Path, default=DEFAULT_PROBE_CONFIG)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--source-type", default="VM", help="source.type to include (default: VM)")
    args = parser.parse_args()

    probe_source = args.probe.read_text(encoding="utf-8")
    probe_config = args.probe_config.read_text(encoding="utf-8") if args.probe_config.exists() else ""
    filtered = build_filtered_spec(args.spec, args.source_type)
    spec_json = json.dumps(filtered, indent=2, ensure_ascii=False)

    delimiters = {
        "PROBE_PY_EOF": probe_source,
        "SPEC_JSON_EOF": spec_json,
        "PROBE_TOML_EOF": probe_config,
    }
    for delimiter, content in delimiters.items():
        if delimiter in content:
            raise SystemExit(
                f"Heredoc delimiter collision: embedded content contains '{delimiter}'. "
                "Rename the delimiters in the template."
            )

    script = SCRIPT_TEMPLATE.format(
        probe_source=probe_source,
        spec_json=spec_json,
        probe_config=probe_config,
        n_tests=len(filtered["tests"]),
        source_type=args.source_type,
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(script, encoding="utf-8")
    args.out.chmod(0o755)
    print(f"✅ Generated {args.out} ({len(filtered['tests'])} tests, source.type={args.source_type})")


if __name__ == "__main__":
    sys.exit(main())
